config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "user#show"
  resources :user, only: [:new, :create, :index, :show]
  resources :session, only: [:new, :create, :destroy]

  #Session management
  post "login", to: "session#create", as: "login"
  post "register", to: "user#create", as: "register"
  get "logout", to: "session#destroy", as: "logout"

  #Staff functionalities
  get "staff/search", to: "staff#search", as: "staff/search"
  post "staff/query", to: "staff#query", as: "staff/query"
  get "staff/favourites", to: "staff#favourites", as: "staff/favourites"
  get "staff/detail/:id", to: "staff#detail", as: "staff/detail"
  post "staff/create", to: "staff#create", as: "staff/create"
  get "staff/edit", to: "staff#edit", as: "staff/edit"
  post "staff/update", to: "staff#update", as: "staff/update"
  get "staff/destroy", to: "staff#destroy", as: "staff/destroy"
  get "staff/print", to: "staff#print", as: "staff/print"


  get "fullreport/:id", to: "fullreport#show", as: "fullreport"

  #Course functionalities
  get "course/search", to: "course#search", as: "course/search"
  post "course/query", to: "course#query", as: "course/query"
  get "course/favourites", to: "course#favourites", as: "course/favourites"
  get "course/detail/:id", to: "course#detail", as: "course/detail"
  post "course/create", to: "course#create", as: "course/create"
  get "course/edit", to: "course#edit", as: "course/edit"
  post "course/update", to: "course#update", as: "course/update"
  get "course/destroy", to: "course#destroy", as: "course/destroy"
  get "course/print", to: "course#print", as: "course/print"

  #Project functionalities
  get "project/search", to: "project#search", as: "project/search"
  post "project/query", to: "project#query", as: "project/query"
  get "project/favourites", to: "project#favourites", as: "project/favourites"
  get "project/detail/:id", to: "project#detail", as: "project/detail"
  post "project/create", to: "project#create", as: "project/create"
  get "project/edit", to: "project#edit", as: "project/edit"
  post "project/update", to: "project#update", as: "project/update"
  get "project/destroy", to: "project#destroy", as: "project/destroy"
  get "project/print", to: "project#print", as: "project/print"

  #Thesis functionalities
  get "thesis/search", to: "thesis#search", as: "thesis/search"
  post "thesis/query", to: "thesis#query", as: "thesis/query"
  get "thesis/favourites", to: "thesis#favourites", as: "thesis/favourites"
  get "thesis/detail/:id", to: "thesis#detail", as: "thesis/detail"
  post "thesis/create", to: "thesis#create", as: "thesis/create"
  get "thesis/edit", to: "thesis#edit", as: "thesis/edit"
  post "thesis/update", to: "thesis#update", as: "thesis/update"
  get "thesis/destroy", to: "thesis#destroy", as: "thesis/destroy"
  get "thesis/print", to: "thesis#print", as: "thesis/print"

end

app/controllers/thesis_controller.rb
# Controller used for all thesis functionalities (Search/Detail View/ Favourite Management)
# "extending" from the BaseController
class ThesisController < BaseController

  # display of the users' favourites
  def favourites
    @favourites = load_favourite_bundle(current_user.thesis_favourites)
    # "calculation" of the results to display on the current page of the results
    @favourites["slice"] = @favourites["objects"].slice(PAGE_ENTRY_COUNT * (params[:p].to_i - 1), PAGE_ENTRY_COUNT)
  end

  # Creating new favourite (persisting to db)
  def create
    if params[:id]
      unless is_favourite(params[:id])
        current_user.thesis_favourites.create(thesis_id: params[:id], notes: "", keywords: "")
        flash[:notice] = "Thesis " + params["title"].to_s + " added to favourites"
        redirect_back(fallback_location: thesis_search_url)
      end
    end
  end

  # Displays an edit form for a favourite given by the id in params
  def edit
    @favourites = load_favourite_bundle(current_user.thesis_favourites)
    @favourite = current_user.thesis_favourites.where(:id => params["id"].to_i)[0]
    @fav_name = get_fav_name(params["id"].to_i)
  end

  # Update fields of a thesis-favourite given by id in params
  # This is where the data from the edit form is posted to and processed
  def update
    @favourite = current_user.thesis_favourites.where(:id => params["id"].to_i)[0]
    if @favourite.update(favourite_params)
      flash[:notice] = "Updated"
    else
      flash[:notice] = "Error updating"
    end
    redirect_to thesis_favourites_path(p: 1)
  end

  # removing a favourite
  def destroy
    if params[:id]
      @favourite = current_user.thesis_favourites.where(:id => params["id"].to_i)[0]
      @favourite.destroy
      flash[:notice] = "Deleted"
      redirect_to thesis_favourites_path(p: 1)
    end
  end

  # print functionality to provide a printable list of all favourites
  def print
    @favourites = load_favourite_bundle(current_user.thesis_favourites)['objects']
  end

  helper_method :is_favourite # used for case distinction when rendering detail information
  helper_method :get_favourite_data # used for rendering detail information
  helper_method :get_fav_url # override from base since the url is different for each controller, needed for sorting

  private


  # ############################################################################################
  #
  #     Helper methods here
  #     Helpers used for displaying data in the HTML
  #
  # ############################################################################################

  # checks if the thesis with given id is a favourite of the current user
  def is_favourite(id)
    current_user.thesis_favourites.each do |f|
      return true if f["thesis_id"].to_s == id.to_s
    end
    return false
  end

  # helper method used to get the (persisted) data of a users thesis favourite
  def get_favourite_data(id)
    current_user.thesis_favourites.each do |f|
      return f if f["thesis_id"].to_s == id.to_s
    end
    return nil
  end

  # helper for displaying the name of a favourite given the database id of it
  def get_fav_name(fav_id)
    ret = "Name not found"
    @favourites["objects"].each do |f|
      if f["fav_id"] == fav_id
        ret = f["title"]
      end
    end
    ret
  end

  # override from base since the url is different for each controller
  # this is needed in order to do all sorting in a single "master" partial (_favourites.html.erb)
  def get_fav_url
    return thesis_favourites_url(:p => 1)
  end

  # ############################################################################################
  #
  #     DB and API pull methods here
  #     These methods are used for getting the data from the API and the DB
  #     and formatting it so that it can be presented in the HTML
  #
  # ############################################################################################


  # override of base_controller
  def fetch_url
    return BASE_API_URL + THESIS_FETCH_URI
  end

  # override of base_controller
  def search_url
    return BASE_API_URL + THESIS_SEARCH_URI
  end

  # override of base_controller
  def search_params
    "&max_treffer=" + MAX_HITS.to_s
  end

  # override of base_controller since results are XMLs
  def fetch_parse(http_result)
    return Hash.from_xml(http_result.body.to_s)["tuvienna"]["thesis"]
  end

  # creates an object containing all the (persisted) information of a favourite course
  # combined with the available API data
  # used in load_favourite_bundle (defined in base_controller)
  def create_fav_object(favourite)
    obj = api_fetch(favourite.thesis_id)
    obj["fav_id"] = favourite.id
    obj["id"] = favourite.thesis_id
    obj["notes"] = favourite.notes
    obj["keywords"] = favourite.keywords
    obj["date"] = favourite["created_at"]
    if obj["title"]["en"].nil?
      obj["sort_title"] = obj["title"]["de"]
    else
      obj["sort_title"] = obj["title"]["en"]
    end
    return obj
  end

  # ############################################################################################
  #
  #     Typing methods here
  #     These methods are used for strong typing of user input data
  #
  # ############################################################################################

  # Strong typing for edit form
  def favourite_params
    params.require(:thesis_favourite).permit(:notes, :keywords)
  end


end

app/helpers/thesis_helper.rb
module ThesisHelper
end

app/views/thesis/_favourite_result.html.erb
<% if favourite["title"]["en"].nil? %>
  <h2> <%= favourite["title"]["de"] %></h2>
<% else %>
  <h2> <%= favourite["title"]["en"] %></h2>
<% end %>

<h3>
  <%= favourite["notes"] %>
</h3>
<h4>
  <%= favourite["keywords"] %>
</h4>

<h2>
  <%= link_to "[Details]", thesis_detail_path(favourite["id"]) %>
  <%= link_to "[Edit]", thesis_edit_path(id: favourite["fav_id"]) %>
  <%= link_to "[Remove]", thesis_destroy_path(id: favourite["fav_id"]) %>
</h2>



app/views/thesis/_footer.html.erb
<%= link_to "[Thesis search]", "search" %>
<%= link_to "[Return to Main Menu]", current_user %>

app/views/thesis/_print_result.html.erb
<% if favourite["title"]["en"].nil? %>
  <h2> <%= favourite["title"]["de"] %></h2>
<% else %>
  <h2> <%= favourite["title"]["en"] %></h2>
<% end %>
<% if params[:annotations].to_i == 1 %>
  <h3>
    <%= favourite["notes"] %>
  </h3>
  <h4>
    <%= favourite["keywords"] %>
  </h4>
<% end %>

app/views/thesis/_search_result.html.erb
<%= result["title"] %><br>
<%= link_to "[Details]", thesis_detail_url(result["id"]) %>
<% unless is_favourite(result["id"]) %>
  <%= form_tag(thesis_create_path, method: :post) do %>
    <%= hidden_field_tag(:id, result["id"]) %>
    <%= hidden_field_tag(:title, result["title"]) %>
    <%= submit_tag("[Add to Favourites]",:class => "link") %>
  <% end %>
<% end %>




app/views/thesis/detail.html.erb
<% if @result["title"]["en"].nil? %>
  <h1> <%= @result["title"]["de"] %></h1>
<% else %>
  <h1> <%= @result["title"]["en"] %></h1>
<% end %>

<hr>
<h3>Type: <%= @result["thesisType"] %></h3>
<div class="details">
  <h2>Thesis Details</h2>
  <% unless @result["instituteCode"].nil? %>
    <p><b>Institute code:</b> <%= @result["instituteCode"].html_safe %></p>
  <% end %>

  <% unless @result["instituteName"].nil? %>
    <p><b>Institute Name:</b> <%= @result["instituteName"]["en"].html_safe %></p>
  <% end %>

  <% unless @result["facultyCode"].nil? %>
    <p><b>Faculty Code:</b> <%= @result["facultyCode"].html_safe %></p>
  <% end %>

  <% unless @result["facultyName"].nil? %>
    <p><b>Faculty Name:</b> <%= @result["facultyName"]["en"].html_safe %></p>
  <% end %>

  <% if @result["keywords"]["en"].nil? %>
    <% unless @result["keywords"]["de"].nil? %>
      <p><b>Keywords:</b> <%= @result["keywords"]["de"].html_safe %></p>
    <% end %>
  <% else %>
    <p><b>Keywords:</b> <%= @result["keywords"]["en"].html_safe %></p>
  <% end %>


  <% unless @result["offeredLanguage"].nil? %>
    <p><b>Offered Language:</b> <%= @result["offeredLanguage"].html_safe %></p>
  <% end %>

  <h2>Advisors</h2>
  <p><b>Advisor:</b>
    <% unless @result["advisor"]["prefixTitle"].nil? %>
      <%= @result["advisor"]["prefixTitle"].html_safe %>
    <% end %>
    <%= @result["advisor"]["givenName"].html_safe %>
    <%= @result["advisor"]["familyName"].html_safe %>
    <% unless @result["advisor"]["postfixTitle"].nil? %>
      <%= @result["advisor"]["postfixTitle"].html_safe %>
    <% end %>
  </p>
  <% unless @result["assistant"].nil? %>
  <p><b>Assistant:</b>
    <% unless @result["assistant"]["prefixTitle"].nil? %>
      <%= @result["assistant"]["prefixTitle"].html_safe %>
    <% end %>
    <%= @result["assistant"]["givenName"].html_safe %>
    <%= @result["assistant"]["familyName"].html_safe %>
    <% unless @result["assistant"]["postfixTitle"].nil? %>
      <%= @result["assistant"]["postfixTitle"].html_safe %>
    <% end %>
  </p>
    <h2>Details</h2>
    <% unless @result["url"].nil? %>
      <p><b>URL:</b> <a href="<%= @result["url"].html_safe %>"><%= @result["url"].html_safe %></a></p>
    <% end %>
  <% end %>
  <% if is_favourite(params[:id]) %>
    <h2>Favourite information:</h2>
    <p>Notes: <%= get_favourite_data(params[:id])["notes"] %></p>
    <p>Keywords: <%= get_favourite_data(params[:id])["keywords"] %></p>
  <% end %>
</div>
<div class="block">
  <%= link_to "[Staff]", staff_search_path %>
  <%= link_to "[Courses]", course_search_path %>
  <%= link_to "[Projects]", project_search_path %>
  <% unless is_favourite(params[:id]) %>
    <%= form_tag(thesis_create_path, method: :post) do %>
      <%= hidden_field_tag(:id, params[:id]) %>
      <%= hidden_field_tag(:title, @result["title"]["en"]) %>
      <%= submit_tag("[Add to Favourites]",:class => "link") %>
    <% end %>
  <% end %>
</div>

app/views/thesis/edit.html.erb
<h1> Edit notes and keywords for <%= @fav_name["en"] %></h1>

<%= form_with model: @favourite, url: thesis_update_path(id: @favourite["id"]), method: :post do |form| %>
  <div>
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>
  <div>
    <%= form.label :keywords %>
    <%= form.text_field :keywords %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<h2>
  <%= link_to "[Back to Thesis Favourites]", thesis_favourites_path(:p => 1) %>
</h2>


app/views/thesis/favourites.html.erb
<h1>Thesis favourites</h1>

<%= render "base/favourites" %>

app/views/thesis/print.html.erb
<div class="printnav">
  <%= link_to '[Print]', 'placeholder', :onclick => 'window.print();return false;'%>
  <% if params[:annotations].to_i == 1 %>
    <%= link_to "[Toggle annotations]", thesis_print_path(:annotations => 0)%>
  <% else %>
    <%= link_to "[Toggle annotations]", thesis_print_path(:annotations => 1)%>
  <% end %>
</div>
<h1>Thesis Favourites</h1>
<%= render "base/print" %>

app/views/thesis/search.html.erb
<h1> Thesis search</h1>

<%= form_tag(thesis_search_url, method: :get) do %>
  <%= text_field_tag(:q, params[:q]) %>
  <%= hidden_field_tag :p, 1 %>
  <div class="center"><%= submit_tag("Search") %></div>
<% end %>

<%= render "base/search", search_url:thesis_search_url.to_s %>