config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "user#show"
  resources :user, only: [:new, :create, :index, :show]
  resources :session, only: [:new, :create, :destroy]

  #Session management
  post "login", to: "session#create", as: "login"
  post "register", to: "user#create", as: "register"
  get "logout", to: "session#destroy", as: "logout"

  #Staff functionalities
  get "staff/search", to: "staff#search", as: "staff/search"
  post "staff/query", to: "staff#query", as: "staff/query"
  get "staff/favourites", to: "staff#favourites", as: "staff/favourites"
  get "staff/detail/:id", to: "staff#detail", as: "staff/detail"
  post "staff/create", to: "staff#create", as: "staff/create"
  get "staff/edit", to: "staff#edit", as: "staff/edit"
  post "staff/update", to: "staff#update", as: "staff/update"
  get "staff/destroy", to: "staff#destroy", as: "staff/destroy"
  get "staff/print", to: "staff#print", as: "staff/print"


  get "fullreport/:id", to: "fullreport#show", as: "fullreport"

  #Course functionalities
  get "course/search", to: "course#search", as: "course/search"
  post "course/query", to: "course#query", as: "course/query"
  get "course/favourites", to: "course#favourites", as: "course/favourites"
  get "course/detail/:id", to: "course#detail", as: "course/detail"
  post "course/create", to: "course#create", as: "course/create"
  get "course/edit", to: "course#edit", as: "course/edit"
  post "course/update", to: "course#update", as: "course/update"
  get "course/destroy", to: "course#destroy", as: "course/destroy"
  get "course/print", to: "course#print", as: "course/print"

  #Project functionalities
  get "project/search", to: "project#search", as: "project/search"
  post "project/query", to: "project#query", as: "project/query"
  get "project/favourites", to: "project#favourites", as: "project/favourites"
  get "project/detail/:id", to: "project#detail", as: "project/detail"
  post "project/create", to: "project#create", as: "project/create"
  get "project/edit", to: "project#edit", as: "project/edit"
  post "project/update", to: "project#update", as: "project/update"
  get "project/destroy", to: "project#destroy", as: "project/destroy"
  get "project/print", to: "project#print", as: "project/print"

  #Thesis functionalities
  get "thesis/search", to: "thesis#search", as: "thesis/search"
  post "thesis/query", to: "thesis#query", as: "thesis/query"
  get "thesis/favourites", to: "thesis#favourites", as: "thesis/favourites"
  get "thesis/detail/:id", to: "thesis#detail", as: "thesis/detail"
  post "thesis/create", to: "thesis#create", as: "thesis/create"
  get "thesis/edit", to: "thesis#edit", as: "thesis/edit"
  post "thesis/update", to: "thesis#update", as: "thesis/update"
  get "thesis/destroy", to: "thesis#destroy", as: "thesis/destroy"
  get "thesis/print", to: "thesis#print", as: "thesis/print"

end

app/controllers/staff_controller.rb
# Controller used for all staff functionalities (Search/Detail View/ Favourite Management)
# "extending" from the BaseController
class StaffController < BaseController

  # display of the users' favourites
  def favourites
    @favourites = load_favourite_bundle(current_user.staff_favourites)
    # "calculation" of the results to display on the current page of the results
    @favourites["slice"] = @favourites["objects"].slice(PAGE_ENTRY_COUNT * (params[:p].to_i - 1), PAGE_ENTRY_COUNT)
  end

  # Creating new favourite (persisting to db)
  def create
    if params[:id]
      unless is_favourite(params[:id])
        current_user.staff_favourites.create(staff_id: params[:id], notes: "", keywords: "")
        flash[:notice] = "User " + params["name"].to_s + " added to favourites"
        redirect_back(fallback_location: staff_search_url)
      end
    end
  end

  # Displays an edit form for a favourite given by the id in params
  def edit
    @favourites = load_favourite_bundle(current_user.staff_favourites)
    @favourite = current_user.staff_favourites.where(:id => params["id"].to_i)[0]
    @fav_name = get_fav_name(params["id"].to_i)
  end

  # Update fields of a staff-favourite given by id in params
  # This is where the data from the edit form is posted to and processed
  def update
    @favourite = current_user.staff_favourites.where(:id => params["id"].to_i)[0]
    if @favourite.update(favourite_params)
      flash[:notice] = "Updated"
    else
      flash[:notice] = "Error updating"
    end
    redirect_to staff_favourites_path(p: 1)
  end

  # delete staff favourite entry
  def destroy
    if params[:id]
      @favourite = current_user.staff_favourites.where(:id => params["id"].to_i)[0]
      @favourite.destroy
      flash[:notice] = "Deleted"
      redirect_to staff_favourites_path(p: 1)
    end
  end

  # print functionality to provide a printable list of all favourites
  def print
    @favourites = load_favourite_bundle(current_user.staff_favourites)['objects']
  end

  helper_method :is_favourite # used for case distinction when rendering detail information
  helper_method :get_favourite_data # used for rendering detail information
  helper_method :get_fav_url # override from base since the url is different for each controller, needed for sorting

  private


  # ############################################################################################
  #
  #     Helper methods here
  #     Helpers used for displaying data in the HTML
  #
  # ############################################################################################

  # checks if the staff member with given tiss_id is a favourite of the current user
  def is_favourite(tiss_id)
    current_user.staff_favourites.each do |f|
      return true if f["staff_id"] == tiss_id
    end
    return false
  end

  # helper method used to get the (persisted) data of a users staff favourite
  def get_favourite_data(tiss_id)
    current_user.staff_favourites.each do |f|
      return f if f["staff_id"] == tiss_id
    end
    return nil
  end

  # override from base since the url is different for each controller
  # this is needed in order to do all sorting in a single "master" partial (_favourites.html.erb)
  def get_fav_url
    return staff_favourites_url(:p => 1)
  end

  # helper for displaying the name of a favourite given the database id of it
  def get_fav_name(fav_id)
    ret = "Name not found"
    @favourites["objects"].each do |f|
      if f["fav_id"] == fav_id
        ret = f["first_name"] + " " + f["last_name"]
      end
    end
    ret
  end

  # ############################################################################################
  #
  #     DB and API pull methods here
  #     These methods are used for getting the data from the API and the DB
  #     and formatting it so that it can be presented in the HTML
  #
  # ############################################################################################

  # override of base_controller
  def fetch_url
    return BASE_API_URL + STAFF_FETCH_URI
  end

  # override of base_controller
  def search_url
    return BASE_API_URL + STAFF_SEARCH_URI
  end

  # override of base_controller
  def search_params
    "&max_treffer=" + MAX_HITS.to_s
  end

  # ############################################################################################
  #
  #     Typing methods here
  #     These methods are used for strong typing of user input data
  #
  # ############################################################################################

  # Strong typing for edit form
  def favourite_params
    params.require(:staff_favourite).permit(:notes, :keywords)
  end



end

app/helpers/staff_helper.rb
module StaffHelper
end

app/views/staff/_favourite_result.html.erb
<h2>
  <%= favourite["first_name"] %>
  <%= favourite["last_name"] %>
</h2>

<h3>
  <%= favourite["notes"] %>
</h3>
<h4>
  <%= favourite["keywords"] %>
</h4>

<h2>
  <%= link_to "[Details]", staff_detail_url(favourite["tiss_id"]) %>
  <%= link_to "[Edit]", staff_edit_path(id: favourite["fav_id"]) %>
  <%= link_to "[Remove]", staff_destroy_path(id: favourite["fav_id"]) %>
</h2>

app/views/staff/_footer.html.erb
<%= link_to "[Staff search]", "search" %>
<%= link_to "[Return to Main Menu]", current_user %>

app/views/staff/_print_result.html.erb
<h2>
  <%= favourite["first_name"] %>
  <%= favourite["last_name"] %>
</h2>
<% if params[:annotations].to_i == 1 %>
  <h3>
    <%= favourite["notes"] %>
  </h3>
  <h4>
    <%= favourite["keywords"] %>
  </h4>
<% end %>



app/views/staff/_search_result.html.erb
<%= result["first_name"] %>
<%= result["last_name"] %><br>
<%= link_to "[Details]", staff_detail_url(result["tiss_id"]) %>
<% unless is_favourite(result["tiss_id"]) %>
  <%= form_tag(staff_create_path, method: :post) do %>
    <%= hidden_field_tag(:id, result["tiss_id"]) %>
    <%= hidden_field_tag(:name, result["first_name"] + " " + result["last_name"]) %>
    <%= submit_tag("[Add to Favourites]",:class => "link") %>
  <% end %>
<% end %>

app/views/staff/detail.html.erb
<h1>Person details</h1>

<h3><%= @result["preceding_titles"] %></h3>
<h2><%= @result["first_name"] %> <%= @result["last_name"] %></h2>
<h3><%= @result["postpositioned_titles"] %></h3>
<% unless @result["picture_uri"].nil? %>
  <img src="<%= BASE_URL %><%= @result["picture_uri"] %>">
<% end %>
<div class="details">
<p>Gender: <%= @result["gender"] %></p>
<p>Main phone number: <%= @result["main_phone_number"] %></p>
<p>Main email: <%= @result["main_email"] %></p>
  <% if is_favourite(@result["tiss_id"]) %>
    <br>
    <p>Favourites data:</p>
    <p>Notes: <%= get_favourite_data(@result["tiss_id"])["notes"] %></p>
    <p>Keywords: <%= get_favourite_data(@result["tiss_id"])["keywords"] %></p>
  <% end %>
</div>
<div>
  <%= link_to "[Fullreport]",  fullreport_url(@result["tiss_id"]) %>
</div>
<div class="block">
<%= link_to "[Courses]", course_search_path %>
<%= link_to "[Projects]", project_search_path %>
<%= link_to "[Theses]", thesis_search_path %>
  <% unless is_favourite(@result["tiss_id"]) %>
    <%= form_tag(staff_create_path, method: :post) do %>
      <%= hidden_field_tag(:id, @result["tiss_id"]) %>
      <%= hidden_field_tag(:name, @result["first_name"] + " " + @result["last_name"]) %>
      <%= submit_tag("[Add to Favourites]",:class => "link") %>
    <% end %>
    <% end %>
</div>

app/views/staff/edit.html.erb
<h1> Edit notes and keywords for <%= @fav_name %></h1>

<%= form_with model: @favourite, url: staff_update_path(id: @favourite["id"]), method: :post do |form| %>
  <div>
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>
  <div>
    <%= form.label :keywords %>
    <%= form.text_field :keywords %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<h2>
  <%= link_to "[Back to Staff Favourites]", staff_favourites_url(:p => 1) %>
</h2>

app/views/staff/favourites.html.erb
<h1>Staff favourites</h1>

<%= render "base/favourites" %>

app/views/staff/print.html.erb
<div class="printnav">
  <%= link_to '[Print]', 'placeholder', :onclick => 'window.print();return false;'%>
  <% if params[:annotations].to_i == 1 %>
    <%= link_to "[Toggle annotations]", staff_print_path(:annotations => 0)%>
  <% else %>
    <%= link_to "[Toggle annotations]", staff_print_path(:annotations => 1)%>
  <% end %>
</div>
<h1>Staff Favourites</h1>
<%= render "base/print" %>

app/views/staff/search.html.erb
<h1> Staff search</h1>

<%= form_tag(staff_search_url, method: :get) do %>
  <%= text_field_tag(:q, params[:q]) %>
  <%= hidden_field_tag :p, 1 %>
  <div class="center"><%= submit_tag("Search") %></div>
<% end %>

<%= render "base/search", search_url:staff_search_url.to_s %>