config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "user#show"
  resources :user, only: [:new, :create, :index, :show]
  resources :session, only: [:new, :create, :destroy]

  #Session management
  post "login", to: "session#create", as: "login"
  post "register", to: "user#create", as: "register"
  get "logout", to: "session#destroy", as: "logout"

  #Staff functionalities
  get "staff/search", to: "staff#search", as: "staff/search"
  post "staff/query", to: "staff#query", as: "staff/query"
  get "staff/favourites", to: "staff#favourites", as: "staff/favourites"
  get "staff/detail/:id", to: "staff#detail", as: "staff/detail"
  post "staff/create", to: "staff#create", as: "staff/create"
  get "staff/edit", to: "staff#edit", as: "staff/edit"
  post "staff/update", to: "staff#update", as: "staff/update"
  get "staff/destroy", to: "staff#destroy", as: "staff/destroy"
  get "staff/print", to: "staff#print", as: "staff/print"


  get "fullreport/:id", to: "fullreport#show", as: "fullreport"

  #Course functionalities
  get "course/search", to: "course#search", as: "course/search"
  post "course/query", to: "course#query", as: "course/query"
  get "course/favourites", to: "course#favourites", as: "course/favourites"
  get "course/detail/:id", to: "course#detail", as: "course/detail"
  post "course/create", to: "course#create", as: "course/create"
  get "course/edit", to: "course#edit", as: "course/edit"
  post "course/update", to: "course#update", as: "course/update"
  get "course/destroy", to: "course#destroy", as: "course/destroy"
  get "course/print", to: "course#print", as: "course/print"

  #Project functionalities
  get "project/search", to: "project#search", as: "project/search"
  post "project/query", to: "project#query", as: "project/query"
  get "project/favourites", to: "project#favourites", as: "project/favourites"
  get "project/detail/:id", to: "project#detail", as: "project/detail"
  post "project/create", to: "project#create", as: "project/create"
  get "project/edit", to: "project#edit", as: "project/edit"
  post "project/update", to: "project#update", as: "project/update"
  get "project/destroy", to: "project#destroy", as: "project/destroy"
  get "project/print", to: "project#print", as: "project/print"

  #Thesis functionalities
  get "thesis/search", to: "thesis#search", as: "thesis/search"
  post "thesis/query", to: "thesis#query", as: "thesis/query"
  get "thesis/favourites", to: "thesis#favourites", as: "thesis/favourites"
  get "thesis/detail/:id", to: "thesis#detail", as: "thesis/detail"
  post "thesis/create", to: "thesis#create", as: "thesis/create"
  get "thesis/edit", to: "thesis#edit", as: "thesis/edit"
  post "thesis/update", to: "thesis#update", as: "thesis/update"
  get "thesis/destroy", to: "thesis#destroy", as: "thesis/destroy"
  get "thesis/print", to: "thesis#print", as: "thesis/print"

end

app/models/user.rb
# User model used to store User objects which can have many staff/course/project/thesis favourites
class User < ApplicationRecord
  has_many :staff_favourites
  has_many :course_favourites
  has_many :project_favourites
  has_many :thesis_favourites

  validates :username, uniqueness: true # make sure the username is unique
  validates_confirmation_of :password # make sure password has been confirmed

  # Welcome message displayed when user is successfully logged in
  def welcome
    "Hello, #{self.username}!"
  end
end

app/controllers/user_controller.rb
# UserController is the controller handling user management (registration of new users, rendering user profile page)
class UserController < ApplicationController

    # Skip the login requirement since UserController#create is used to register a new user
    # and must therefore be accessible for not logged in users
    skip_before_action :require_login, only: [:new,:create]

    # User registration
    def new
        @user = User.new
    end

    # Renders the currently logged in user's profile page
    def show
        @user = User.find_by(id: session[:user_id])
    end

    # POST endpoint which the data of the user registration form is POSTed to
    # inputs are validated by user_controller#user_params
    def create
        @user = User.new(user_params)
        if user_params[:password] != user_params[:password_confirmation] # check if both given passwords match
            flash[:notice] = "Passwords did not match"
            redirect_to new_user_path
        elsif User.find_by(username: @user.username) # check if username is already taken
            flash[:notice] = "Username already taken!"
            redirect_to new_user_path
        elsif @user.save # try to persist new user
            flash[:notice] = "Registration successful! Login in now!"
            redirect_to new_session_path
        else # something went wrong persisting
            flash[:notice] = "Error persisting new user"
            redirect_to new_user_path
        end
    end

    def destroy
    end

    private

    # validation of form input
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/new.html.erb
<h1> Sign up</h1>
<%= form_with url:register_path, model:@user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>
  <br>
  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </div>
  <br>
  <div>
    <%= form.submit "Register now" %>
    <%= link_to "[Back to Login]", new_session_path, method: :get  %>
  </div>

<% end %>

app/views/user/show.html.erb
<h1> Home Page</h1>
<%= content_tag :h1, current_user.welcome %>
<br>
<table>
  <tr>
    <td>
      Searches:
    </td>
  <tr>
    <td><%= link_to "[Staff search]", staff_search_path %></td>
    <td><%= link_to "[Course search]", course_search_path %></td>
    <td><%= link_to "[Project search]", project_search_path %></td>
    <td><%= link_to "[Thesis search]", thesis_search_path %></td>
  </tr>
  <tr>
    <td>
      Favourites:
    </td>
  </tr>
  <tr>
    <td><%= link_to "[Staff favourites]", staff_favourites_url(:p => 1) %></td>
    <td><%= link_to "[Course favourites]", course_favourites_path(:p => 1) %></td>
    <td><%= link_to "[Project favourites]", project_favourites_path(:p => 1) %></td>
    <td><%= link_to "[Thesis favourites]", thesis_favourites_path(:p => 1) %></td>
  </tr>
  <tr>
    <td>
      Reporting:
    </td>
  </tr>
  <tr>
    <td><%= link_to "[Staff reporting]", staff_print_path(:annotations => 1)%></td>
    <td><%= link_to "[Course reporting]", course_print_path(:annotations => 1)%></td>
    <td><%= link_to "[Project reporting]", project_print_path(:annotations => 1)%></td>
    <td><%= link_to "[Thesis reporting]", thesis_print_path(:annotations => 1)%></td>
  </tr>
</table>